name: pr-validation-wf
on: 
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop
jobs: 
  pr-validation-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome steps
        run: echo "welcome to github Actions" 
      - name: second step
        run: echo "welcome Actions" 
  second-job: 
   runs-on: ubuntu-latest
   steps:
     - name: first step job2
       run: echo "this is first step job2"


